tasks:
  - tox -e py27-django16
  - tox -e py27-django17
  - tox -e py34-django16
  - tox -e py34-django17
  - flake8
  - isort -c -rc holonet_django tests
  - coverage combine && coverage report -m --fail-under=75
  - coverage xml

comment: false

coverage:
  path: coverage.xml
  parser: python
