tasks:
  - tox -e py27-django17
  - tox -e py34-django17
  - tox -e py27-django18
  - tox -e py34-django18
  - tox -e py27-django19
  - tox -e py34-django19
  - tox -e docs
  - tox -e flake8
  - tox -e isort
  - tox -e coverage

comment: false

verbose_tasks:
  - tox -e coverage

coverage:
  path: coverage.xml
  parser: python
