tasks:
  - tox -e py27-django15
  - tox -e py27-django16
  - tox -e py27-django17
  - tox -e py34-django15
  - tox -e py34-django16
  - tox -e py34-django17
  - coverage combine && coverage report -m
  - flake8

comment: false
